language: perl
sudo: false
os:
  - linux
#  - osx
# osx has still no perlbrew nor cpanm. which is bad, because darwin is buggy

perl:
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'

script:
  - perl Makefile.PL && make && make test

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
